name: CI

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate package
        uses: hapakaien/archlinux-package-action@v2
        with:
          path: package
          flags: '-s --noconfirm'
          namcap: false
        
      - name: Upload package to Release
        uses: ncipollo/release-action@main
        with:
          tag: v${{ steps.branch-name.outputs.tag }}
          name: v${{ steps.branch-name.outputs.tag }}
          body: ${{ steps.changelog-reader.outputs.changes }}
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
        
