name: CI

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate package
        uses: hapakaien/archlinux-package-action@v2
        
      - name: Upload package to Release
        uses: ncipollo/release-action@main
        with:
          tag: v2022-12-14
          artifacts: /home/builder/gh-action/*.pkg.tar.zst
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
        
