name: CI

on:
  push:
    tags:
    - '*'

jobs:
  build_x86_64:
    strategy:
      matrix:
        PKGBUILDs: [oss-cad-suite-build-bin]

      fail-fast: false
      
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Non-AUR packages
        id: makepkg
        uses: ./build-x86_64
        with:
          pkgdir: ${{ matrix.PKGBUILDs }}
          aurDeps: true
          
      - uses: actions/upload-artifact@v3
        with:
          path: ./*/*.pkg.tar.zst
          name: ${{ matrix.PKGBUILDs }}
          if-no-files-found: error
      
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ${{ steps.makepkg.outputs.pkgfile0 }}
          token: ${{ secrets.GH_TOKEN }}

  build_aarch64:
    strategy:
      matrix:
        PKGBUILDs: [oss-cad-suite-build-bin]

      fail-fast: false
      
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Non-AUR packages
        id: makepkg
        uses: ./build-aarch64
        with:
          pkgdir: ${{ matrix.PKGBUILDs }}
          aurDeps: true
          
      - uses: actions/upload-artifact@v3
        with:
          path: ./*/*.pkg.tar.zst
          name: ${{ matrix.PKGBUILDs }}
          if-no-files-found: error
      
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ${{ steps.makepkg.outputs.pkgfile0 }}
          token: ${{ secrets.GH_TOKEN }}     
